Repository project-matching/project-matching-frontend, pull requests merged in 2022-09, with the labels that each got.

#53 feat: post details page 이전 기능 복구
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  src/components/Modals/PositionApplyModal.tsx
  src/components/Post/Comment.tsx
  src/components/Post/Position.tsx
  src/components/Post/Side.tsx
  src/pages/project/[...id].tsx
  src/pages/project/[id].tsx
  src/pages/project/upload.tsx
  src/redux/reducers/components/modals.ts
  src/services/CommentService.ts
  src/services/ProjectService.ts
Labels: feature

#55 Feat/notification page
  src/components/Headers/Notification.tsx
  src/components/Layouts/InfiniteScrollLayout.tsx
  src/pages/bookmark/index.tsx
  src/pages/index.tsx
  src/pages/myproject/applied.tsx
  src/pages/myproject/created.tsx
  src/pages/myproject/joined.tsx
  src/pages/notification/index.tsx
  src/pages/recruited.tsx
  src/pages/recruiting.tsx
  src/pages/results/index.tsx
  src/services/BookmarkService.ts
  src/services/NotificationService.ts
  src/styles/theme.ts
Labels: bug, feature

#56 feat: upload page 구현
  package.json
  src/components/Post/ConfirmModal.tsx
  src/pages/project/[id].tsx
  src/pages/project/upload.tsx
  src/services/ProjectService.ts
  yarn.lock
Labels: feature

#58 feat: publishing admin page & header
  next.config.js
  src/components/Common/Header.tsx
  src/components/Dashboard/DashboardLayout.tsx
  src/components/Dashboard/Position/AddPosition.tsx
  src/components/Dashboard/Position/PositionItem.tsx
  src/components/Dashboard/Position/PositionList.tsx
  src/components/Dashboard/TechStack/AddTechStack.tsx
  src/components/Dashboard/TechStack/TechStackItem.tsx
  src/components/Dashboard/TechStack/TechstackList.tsx
  src/components/Dashboard/User/SearchUser.tsx
  src/components/Dashboard/User/UserCard.tsx
  src/components/Dashboard/User/UserList.tsx
  src/components/Headers/Profile.tsx
  src/components/Layouts/MainSection.tsx
  src/components/Layouts/RoutingSidebar.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/Projects/SmallCard.tsx
  src/components/SearchBar/UserSearchBar.tsx
  src/pages/dashboard/index.tsx
  src/pages/dashboard/notification.tsx
  src/pages/dashboard/position.tsx
  src/pages/dashboard/techStack.tsx
  src/pages/dashboard/user.tsx
  src/pages/index.tsx
  src/redux/sagas/userSaga.ts
  src/styles/reset.ts
Labels: feature

#66 Feat/refresh token
  src/components/Dashboard/User/UserList.tsx
  src/components/Forms/SigninForm.tsx
  src/components/Layouts/SearchInfiniteScrollLayout.tsx
  src/components/Projects/BookmarkProjectLayout.tsx
  src/components/SearchBar/UserSearchBar.tsx
  src/pages/_app.tsx
  src/pages/auth/success.tsx
  src/pages/mypage/change-profile.tsx
  src/pages/mypage/index.tsx
  src/redux/reducers/auth.ts
  src/redux/reducers/users.ts
  src/redux/sagas/authSaga.ts
  src/redux/sagas/userSaga.ts
  src/services/TokenService.ts
  src/services/UserService.ts
  src/type.ts
Labels: bug, feature

#68 fix: token type error
  src/pages/auth/pwd.tsx
  src/pages/auth/signup-fail.tsx
  src/pages/auth/signup.tsx
  src/pages/welcome.tsx
  src/redux/sagas/authSaga.ts
  src/redux/sagas/userSaga.ts
  src/services/UserService.ts
Labels: bug

#74 Fix/image error
  src/components/Buttons/OAuthButton.tsx
  src/components/Dashboard/TechStack/AddTechStack.tsx
  src/components/Dashboard/TechStack/TechStackItem.tsx
  src/components/Dashboard/User/UserCard.tsx
  src/components/Headers/Profile.tsx
  src/components/Headers/ToggleDropdown/ImageToggle.tsx
  src/components/Modals/UserBlockModal.tsx
  src/components/MyPage/MyProfile.tsx
  src/components/MyPage/MyProfileChange.tsx
  src/components/Projects/LargeCard.tsx
  src/components/Projects/SmallCard.tsx
  src/services/AppApi.ts
Labels: bug
