Repository project-matching/project-matching-frontend, pull requests merged in 2022-10, with the labels that each got.

#79 Refactor/header
  src/__test__/index.test.tsx
  src/components/Common/Header.tsx
  src/components/Common/LogoLink.tsx
  src/components/Headers/Notification.tsx
  src/components/Headers/ToggleDropdown/ImageToggle.tsx
  src/components/Layouts/InfiniteScrollLayout.tsx
  src/components/Layouts/SearchInfiniteScrollLayout.tsx
  src/components/Post/Position.tsx
  src/pages/_app.tsx
  src/pages/bookmark/index.tsx
  src/pages/index.tsx
  src/pages/myproject/applied.tsx
  src/pages/myproject/created.tsx
  src/pages/myproject/index.tsx
  src/pages/myproject/joined.tsx
  src/pages/notification/index.tsx
  src/pages/project/[id].tsx
  src/pages/recruited.tsx
  src/pages/recruiting.tsx
  src/pages/welcome.tsx
  src/redux/reducers/auth.ts
  src/redux/sagas/authSaga.ts
  src/redux/sagas/userSaga.ts
  src/services/AppApi.ts
  src/services/UserService.ts
Labels: bug, refactor

#77 Style/detail 수정
  src/components/Inputs/CommentInput.tsx
  src/components/Post/Side.tsx
  src/pages/project/[id].tsx
  src/services/CommentService.ts
Labels: refactor

#84 Fix/project detail
  src/components/Buttons/PrimaryButton.tsx
  src/components/Buttons/SecondaryButton.tsx
  src/components/Modals/PositionApplyModal.tsx
  src/components/Modals/RejectModal.tsx
  src/components/Post/Comment.tsx
  src/components/Post/Position.tsx
  src/components/Post/Side.tsx
  src/pages/project/[id].tsx
  src/styles/reset.ts
Labels: bug, refactor

#93 Docs/readme
  README.md
Labels: documentation

#103 Fix/detail page
  src/components/Buttons/SecondaryButton.tsx
  src/components/Post/Side.tsx
  src/pages/dashboard/techStack.tsx
  src/pages/project/[id].tsx
Labels: bug
